// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/batch-search.html"
    | "/content-scripts/frame-guard.js"
    | "/content-scripts/inject.js"
    | "/icons/icon-128.png"
    | "/icons/icon-16.png"
    | "/icons/icon-32.png"
    | "/icons/icon-48.png"
    | "/icons/icon.svg"
    | "/rules.json"
    | "/sidepanel.html"
    | "/site-handlers.json"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
