import type { ViralExampleDef } from "./types";

export const VIRAL_EXAMPLE_DEFS: ViralExampleDef[] = [
  // 🧩 Brain Teasers (13)
  { queryKey: "brainTeaser_1", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_2", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_3", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_4", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_5", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_6", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_7", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_8", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_9", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_10", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_11", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_12", categoryId: "brainTeaser" },
  { queryKey: "brainTeaser_13", categoryId: "brainTeaser" },

  // 🤖 AI Identity (12)
  { queryKey: "aiIdentity_1", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_2", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_3", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_4", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_5", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_6", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_7", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_8", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_9", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_10", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_11", categoryId: "aiIdentity" },
  { queryKey: "aiIdentity_12", categoryId: "aiIdentity" },

  // ✍️ Creative Writing (14)
  { queryKey: "creative_1", categoryId: "creative" },
  { queryKey: "creative_2", categoryId: "creative" },
  { queryKey: "creative_3", categoryId: "creative" },
  { queryKey: "creative_4", categoryId: "creative" },
  { queryKey: "creative_5", categoryId: "creative" },
  { queryKey: "creative_6", categoryId: "creative" },
  { queryKey: "creative_7", categoryId: "creative" },
  { queryKey: "creative_8", categoryId: "creative" },
  { queryKey: "creative_9", categoryId: "creative" },
  { queryKey: "creative_10", categoryId: "creative" },
  { queryKey: "creative_11", categoryId: "creative" },
  { queryKey: "creative_12", categoryId: "creative" },
  { queryKey: "creative_13", categoryId: "creative" },
  { queryKey: "creative_14", categoryId: "creative" },

  // 💻 Coding Challenge (12)
  { queryKey: "coding_1", categoryId: "coding" },
  { queryKey: "coding_2", categoryId: "coding" },
  { queryKey: "coding_3", categoryId: "coding" },
  { queryKey: "coding_4", categoryId: "coding" },
  { queryKey: "coding_5", categoryId: "coding" },
  { queryKey: "coding_6", categoryId: "coding" },
  { queryKey: "coding_7", categoryId: "coding" },
  { queryKey: "coding_8", categoryId: "coding" },
  { queryKey: "coding_9", categoryId: "coding" },
  { queryKey: "coding_10", categoryId: "coding" },
  { queryKey: "coding_11", categoryId: "coding" },
  { queryKey: "coding_12", categoryId: "coding" },

  // 🎯 Practical Advice (13)
  { queryKey: "advice_1", categoryId: "advice" },
  { queryKey: "advice_2", categoryId: "advice" },
  { queryKey: "advice_3", categoryId: "advice" },
  { queryKey: "advice_4", categoryId: "advice" },
  { queryKey: "advice_5", categoryId: "advice" },
  { queryKey: "advice_6", categoryId: "advice" },
  { queryKey: "advice_7", categoryId: "advice" },
  { queryKey: "advice_8", categoryId: "advice" },
  { queryKey: "advice_9", categoryId: "advice" },
  { queryKey: "advice_10", categoryId: "advice" },
  { queryKey: "advice_11", categoryId: "advice" },
  { queryKey: "advice_12", categoryId: "advice" },
  { queryKey: "advice_13", categoryId: "advice" },

  // 📚 Knowledge Test (12)
  { queryKey: "knowledge_1", categoryId: "knowledge" },
  { queryKey: "knowledge_2", categoryId: "knowledge" },
  { queryKey: "knowledge_3", categoryId: "knowledge" },
  { queryKey: "knowledge_4", categoryId: "knowledge" },
  { queryKey: "knowledge_5", categoryId: "knowledge" },
  { queryKey: "knowledge_6", categoryId: "knowledge" },
  { queryKey: "knowledge_7", categoryId: "knowledge" },
  { queryKey: "knowledge_8", categoryId: "knowledge" },
  { queryKey: "knowledge_9", categoryId: "knowledge" },
  { queryKey: "knowledge_10", categoryId: "knowledge" },
  { queryKey: "knowledge_11", categoryId: "knowledge" },
  { queryKey: "knowledge_12", categoryId: "knowledge" },

  // ⚖️ Hot Takes (12)
  { queryKey: "hotTake_1", categoryId: "hotTake" },
  { queryKey: "hotTake_2", categoryId: "hotTake" },
  { queryKey: "hotTake_3", categoryId: "hotTake" },
  { queryKey: "hotTake_4", categoryId: "hotTake" },
  { queryKey: "hotTake_5", categoryId: "hotTake" },
  { queryKey: "hotTake_6", categoryId: "hotTake" },
  { queryKey: "hotTake_7", categoryId: "hotTake" },
  { queryKey: "hotTake_8", categoryId: "hotTake" },
  { queryKey: "hotTake_9", categoryId: "hotTake" },
  { queryKey: "hotTake_10", categoryId: "hotTake" },
  { queryKey: "hotTake_11", categoryId: "hotTake" },
  { queryKey: "hotTake_12", categoryId: "hotTake" },

  // 🎭 Fun & Personality (12)
  { queryKey: "fun_1", categoryId: "fun" },
  { queryKey: "fun_2", categoryId: "fun" },
  { queryKey: "fun_3", categoryId: "fun" },
  { queryKey: "fun_4", categoryId: "fun" },
  { queryKey: "fun_5", categoryId: "fun" },
  { queryKey: "fun_6", categoryId: "fun" },
  { queryKey: "fun_7", categoryId: "fun" },
  { queryKey: "fun_8", categoryId: "fun" },
  { queryKey: "fun_9", categoryId: "fun" },
  { queryKey: "fun_10", categoryId: "fun" },
  { queryKey: "fun_11", categoryId: "fun" },
  { queryKey: "fun_12", categoryId: "fun" },
];
